# Google's Text to Speech
from gtts import gTTS
# To play the sound generated by GTTS
from playsound import playsound
import os

# Specifying the paths
file = "C:/Pen Projects/Read Aloud/file.txt"
sound = "C:/Pen Projects/Read Aloud/output.mp3"

# Checking if the file already exists
my_file = open(file, "r")
if my_file:
    playsound(sound)
else:
    with open(file, "r") as f:
        text = f.read();
        speech = gTTS(text=text, lang='en')
        speech.save("output.mp3")
        playsound(sound)
